# Setting up the environment

In [ ]:
import numpy as np
import random
import time
import matplotlib.pyplot as plt

In [ ]:
!pip install gymnasium[atari]==0.27.1 -q
!pip install gymnasium[accept-rom-license] -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 19.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 80.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 434.7/434.7 kB 13.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done


In [ ]:
import gymnasium as gym
env = gym.make("ALE/KungFuMaster-v5", obs_type = "grayscale")

/usr/local/lib/python3.9/dist-packages/jax/_src/deprecations.py:51: DeprecationWarning: jax.numpy.DeviceArray is deprecated. Use jax.Array.
  warnings.warn(message, DeprecationWarning)
/usr/local/lib/python3.9/dist-packages/jax/_src/deprecations.py:51: DeprecationWarning: jax.numpy.DeviceArray is deprecated. Use jax.Array.
  warnings.warn(message, DeprecationWarning)
/usr/local/lib/python3.9/dist-packages/gymnasium/utils/passive_env_checker.py:35: UserWarning: WARN: A Box observation space has an unconventional shape (neither an image, nor a 1D vector). We recommend flattening the observation to have only a 1D vector or use a custom policy to properly process the data. Actual observation shape: (210, 160)
  logger.warn(


In [ ]:
env.reset()

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 {'lives': 4, 'episode_frame_number': 0, 'frame_number': 0})

## Description

#### You are a Kung-Fu Master fighting your way through the Evil Wizard’s temple. Your goal is to rescue Princess Victoria, defeating various enemies along the way.

## Action Space

#### 0->NOOP
#### 1->UP
#### 2->RIGHT
#### 3->LEFT
#### 4->DOWN
#### 5->DOWNRIGHT
#### 6->DOWNLEFT
#### 7->RIGHTFIRE
#### 8->LEFTFIRE
#### 9->DOWNFIRE
#### 10->UPRIGHTFIRE
#### 11->UPLEFTFIRE
#### 12->DOWNRIGHTFIRE
#### 13->DOWNLEFTFIRE

## Observation Space

#### obs_type="rgb" -> observation_space=Box(0, 255, (210, 160, 3), np.uint8) ...
#### obs_type="grayscale" -> observation_space=Box(0,255, (210, 160), uint8) ... (we are using this for DQN with MLP)
#### obs_type="ram" -> observation_space=Box(0, 255, (128,), np.uint8)

In [ ]:
#env.action_space

In [ ]:
#env.observation_space

In [ ]:
'''env.reset()
random_action = env.action_space.sample()
observation, reward, terminated, truncated, info = env.step(random_action)

print(f"[Input] Action = {random_action}\n")
print(f"[Output] Observation = {observation}, shape = {observation.shape}")
print(f"[Output] Reward = {reward}")
print(f"[Output] Terminated = {terminated}")
print(f"[Output] Truncated = {truncated}")'''

'env.reset()\nrandom_action = env.action_space.sample()\nobservation, reward, terminated, truncated, info = env.step(random_action)\n\nprint(f"[Input] Action = {random_action}\n")\nprint(f"[Output] Observation = {observation}, shape = {observation.shape}")\nprint(f"[Output] Reward = {reward}")\nprint(f"[Output] Terminated = {terminated}")\nprint(f"[Output] Truncated = {truncated}")'

In [ ]:
'''observation_space = []
reward_list = []

for i in range(1, 101):
    observation = env.reset()
    score = 0
    while True:
        random_action = env.action_space.sample()
        observation, reward, terminated, truncated, info = env.step(random_action)
        score = score + reward
        reward_list.append(reward)
        observation_space.append((observation, random_action, reward, i))
        if terminated:
            print('Random action - ', random_action, ' on iteration', i, '. Score = ', score)
            #time.sleep(0.5)
            break
        #env.render()

env.close()'''

"observation_space = []\nreward_list = []\n\nfor i in range(1, 101):\n    observation = env.reset()\n    score = 0\n    while True:\n        random_action = env.action_space.sample()\n        observation, reward, terminated, truncated, info = env.step(random_action)\n        score = score + reward\n        reward_list.append(reward)\n        observation_space.append((observation, random_action, reward, i))\n        if terminated:\n            print('Random action - ', random_action, ' on iteration', i, '. Score = ', score) \n            #time.sleep(0.5)\n            break\n        #env.render()\n\nenv.close()"

In [ ]:
'''from google.colab.patches import cv2_imshow
for i in range(90, 100):
  cv2_imshow(observation_space[i][0])'''

'from google.colab.patches import cv2_imshow\nfor i in range(90, 100):\n  cv2_imshow(observation_space[i][0])'

In [ ]:
OBS = env.reset()
print(OBS)
obs = env.observation_space
obs

(array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8), {'lives': 4, 'episode_frame_number': 0, 'frame_number': 0})


/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Box(0, 255, (210, 160), uint8)

### DQN with MLP

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPooling2D, Activation, Flatten
from keras.optimizers import Adam
from collections import deque

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
update_counter = 0
N = 20
eps_start = 1
#eps_start = 0.5
eps_decay_rate = 0.95
#eps_min = 0.5
eps_min = 0.05

learning_rate = 0.001
gamma = 0.98
batch_size = 64
#buffer_size = 10_000
obs_dim = env.observation_space.shape
action_dim = env.action_space.n
trained_model = None

In [ ]:
class DQNAgent:
  def __init__(self, action_dim, learning_rate, gamma, batch_size, trained_model):
    self.learning_rate = learning_rate
    self.gamma = gamma
    self.batch_size = batch_size
    #self.buffer_size = buffer_size
    self.obs_dim = obs_dim
    self.action_dim = action_dim

    self.replay_memory = deque(maxlen=512)

    if trained_model == None:
      self.model = self.create_model()
      self.target_model = self.model

    else:
      self.model = trained_model
      self.target_model = self.model

    #self.target_model = self.create_model()
    #self.target_model.set_weights(self.model.get_weights())'''


  def create_model(self):

    model = Sequential()

    #model.add(Flatten())

    model.add(Dense(1024, activation='relu'))
    model.add(Dense(512, activation='relu'))
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(0.2))
    model.add(Flatten())
    model.add(Dense(env.action_space.n, activation='linear'))
    model.compile(optimizer=Adam(learning_rate=learning_rate), loss='mse', metrics=['accuracy'])


    return model

  def select_action(self,epsilon, curr_obs, model):
    if random.random() <= epsilon:
      return random.randint(0, action_dim-1)
    else:
      q_vals = model.predict(curr_obs)
      return np.argmax(q_vals[0])



  def memorize(self, curr_obs, action, reward, next_obs, terminated):
    self.replay_memory.append((curr_obs, action, reward, next_obs, terminated))



  def train(self):
    if len(self.replay_memory) < self.batch_size:
      return

    mini_batch = random.sample(self.replay_memory, self.batch_size)

    for curr_obs, action, reward, next_obs, terminated in mini_batch:
      if not terminated:
        target = reward + gamma* np.amax(self.target_model.predict(next_obs)[0])
      else:
        target = reward

      curr_qval = self.model.predict(curr_obs)
      curr_qval[0][action] = target


      #print(f'in train()\n curr_qval -> {curr_qval}')
      #print(f'in train()\n curr_qval shape -> {curr_qval.shape}')


      x, y = list(),list()

      x.append(curr_obs[0])
      y.append(curr_qval[0])


      self.model.fit(np.array(x), np.array(y), batch_size=self.batch_size, epochs=1, verbose=0)


  def update_model(self):
    global update_counter
    self.target_model.set_weights(self.model.get_weights())
    update_counter = 0


  def dqn(self, episodes=10):

    #self.model = self.create_model()
    #self.target_model = self.model
    #self.target_model = self.create_model()
    #self.target_model.set_weights(self.model.get_weights())




    scores = []
    epsilon = eps_start
    for episode in range(episodes):
      #print('hello')
      print('Episode - ', episode+1)

      #epsilon = eps_start
      curr_obs = env.reset()
      _obs = curr_obs[0]
      terminated = False
      truncated = False

      score = 0
      timestep = 0

      #i = 0
      while not (terminated):
        action = agent.select_action(epsilon, _obs, agent.model)

        next_obs, reward, terminated, truncated, info= env.step(action)


        #i+=1
        # print(f'next_obs {next_obs.shape}')
        # next_obs = next_obs.reshape(next_obs, [1, agent.obs_dim])
        # show_obs = cv2_
      # print(f'num of steps ==> {i}')
        #if i%1000 == 0:
        # cv2_imshow(next_obs)


        agent.memorize(_obs, action, reward, next_obs, terminated)


        _obs = next_obs
        score += reward
        timestep +=1


      if len(agent.replay_memory) > batch_size:
          agent.train()

      global update_counter, N
      if update_counter > N:
        agent.update_model()


      print(f"Exploration rate = {epsilon},", end = "\t")
      #print(epsilon*eps_decay_rate)
      epsilon = max(eps_min, epsilon*eps_decay_rate)


      print(f"completed with {timestep} timesteps, score = {score}", end = '\n')
      scores.append(score)


In [ ]:
agent = DQNAgent(action_dim, learning_rate, gamma, batch_size, trained_model)
agent.dqn()
agent.model.save("MLP_Model_10.h5")

Episode -  1
7/7 [==============================] - 0s 2ms/step
Exploration rate = 1,	completed with 1106 timesteps, score = 100.0
Episode -  2
7/7 [==============================] - 0s 2ms/step
Exploration rate = 0.95,	completed with 1119 timesteps, score = 800.0
Episode -  3
7/7 [==============================] - 0s 2ms/step
Exploration rate = 0.9025,	completed with 744 timesteps, score = 500.0
Episode -  4
7/7 [==============================] - 0s 2ms/step
Exploration rate = 0.8573749999999999,	completed with 733 timesteps, score = 200.0
Episode -  5
7/7 [==============================] - 0s 2ms/step
Exploration rate = 0.8145062499999999,	completed with 946 timesteps, score = 500.0
Episode -  6
7/7 [==============================] - 0s 2ms/step
Exploration rate = 0.7737809374999999,	completed with 948 timesteps, score = 100.0
Episode -  7
7/7 [==============================] - 0s 2ms/step
Exploration rate = 0.7350918906249998,	completed with 1062 timesteps, score = 200.0
Episode -  

In [ ]:
x = keras.models.load_model('MLP_Model_250.h5')

In [ ]:
agent = DQNAgent(action_dim, learning_rate, gamma, batch_size, x)
agent.dqn()
agent.model.save("MLP_Model_500.h5")

Streaming output truncated to the last 5000 lines.
7/7 [==============================] - 0s 2ms/step
Exploration rate = 0.05,	completed with 734 timesteps, score = 0.0
Episode -  245
7/7 [==============================] - 0s 2ms/step
Exploration rate = 0.05,	completed with 610 timesteps, score = 0.0
Episode -  246
7/7 [==============================] - 0s 2ms/step
Exploration rate = 0.05,	completed with 666 timesteps, score = 0.0
Episode -  247
7/7 [==============================] - 0s 2ms/step
Exploration rate = 0.05,	completed with 874 timesteps, score = 100.0
Episode -  248
7/7 [==============================] - 0s 2ms/step
Exploration rate = 0.05,	completed with 521 timesteps, score = 0.0
Episode -  249
7/7 [==============================] - 0s 2ms/step
Exploration rate = 0.05,	completed with 672 timesteps, score = 0.0
Episode -  250
7/7 [==============================] - 0s 2ms/step
Exploration rate = 0.05,	completed with 810 timesteps, score = 0.0


In [ ]:
x = keras.models.load_model('MLP_Model_200.h5')

### Testing

In [ ]:
import gymnasium as gym
import tensorflow as tf
import numpy as np
from tensorflow import keras

trained_model = keras.models.load_model("MLP_Model_500.h5")

import time

curr_obs = env.reset()
_obs = curr_obs[0]

#_obs = tf.reshape(_obs,[1,210,160,1],)
#_obs = tf.cast(_obs,dtype=tf.float32)

terminated = False
truncated = False
scores = 0
ts = 0

'''action = env.action_space.sample()
_obs, reward, terminated, truncated, info = env.step(action)
print("Action taken - ", action)'''

while not terminated:
  #action = np.argmax(trained_model.predict(_obs))

  q_vals = trained_model.predict(_obs)
  action = np.argmax(q_vals[0])

  #action = env.action_space.sample()

  print("Action taken - ", action)
  print("Prediction - ", trained_model.predict(_obs)[0])
  print('_obs - ', _obs)

  next_obs, reward, terminated, truncated, info = env.step(action)
  print('next_obs - ', next_obs)
  print((_obs == next_obs).all())
  _obs = next_obs

  ts += 1
  scores += reward
  #if ts == 1000:
   #break


print('Total Score = ', scores)



/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


7/7 [==============================] - 0s 2ms/step
Action taken -  9
7/7 [==============================] - 0s 2ms/step
Prediction -  [0.7887926  0.79635364 0.7829083  0.7820521  0.79413456 0.7728962
 0.7815904  0.78040695 0.7872382  0.7967599  0.7707251  0.7834747
 0.77191174 0.78726107]
_obs -  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
next_obs -  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
True
7/7 [==============================] - 0s 2ms/step
Action taken -  9
7/7 [==============================] - 0s 2ms/step
Prediction -  [0.7887926  0.79635364 0.7829083  0.7820521  0.79413456 0.7728962
 0.7815904  0.78040695 0.7872382  0.7967599  0.7707251  0.7834747
 0.77191174 0.78726107]
_obs -  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
next_obs -  [[0 0 0 ... 0 0

KeyboardInterrupt: ignored